# Generated by Django 4.2.6 on 2023-11-03 09:29

import App.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('total_answers', models.IntegerField(default=0)),
                ('valid_answers', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Leaderboards',
            },
        ),
        migrations.CreateModel(
            name='ProfilePictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.FileField(storage=App.models.OverwriteStorage(), upload_to='ProfilePictures/Profile')),
                ('cover_picture', models.FileField(storage=App.models.OverwriteStorage(), upload_to='ProfilePictures/Cover')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, default='', max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=50)),
                ('last_name', models.CharField(blank=True, default='', max_length=50)),
                ('bio', models.CharField(blank=True, max_length=250)),
                ('total_validated_answers', models.IntegerField(default=0)),
                ('total_answers', models.IntegerField(default=0)),
                ('total_ratio', models.FloatField(default=0)),
                ('monthly_validated_answers', models.IntegerField(default=0)),
                ('monthly_total_answers', models.IntegerField(default=0)),
                ('monthly_ratio', models.FloatField(default=0)),
                ('color_theme', models.CharField(default='#0e4bf1', max_length=7)),
                ('is_darkmode', models.BooleanField(default=False)),
                ('date_joined', models.DateField(default=datetime.date.today)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('leaderboards', models.ManyToManyField(to='App.leaderboard')),
                ('profile_pictures', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.profilepictures')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', App.models.CustomUserManager()),
            ],
        ),
    ]
