# Generated by Django 4.2.6 on 2023-11-03 16:50

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_user_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepictures',
            name='cover_picture',
        ),
        migrations.AlterField(
            model_name='profilepictures',
            name='profile_picture',
            field=models.FileField(storage=App.models.OverwriteStorage(), upload_to='ProfilePictures/'),
        ),
    ]
