# Generated by Django 4.2.6 on 2023-11-04 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_remove_user_profile_pictures_user_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_posted',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
