# Generated by Django 4.2.6 on 2023-11-04 19:11

import App.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_news_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='position',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='news',
            name='media',
            field=models.FileField(storage=App.models.OverwriteStorage(), upload_to='News/'),
        ),
    ]
