# Generated by Django 4.2.6 on 2023-11-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_news_position_alter_news_date_posted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='media_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
